name: Snyk Security Scan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Snyk CLI
      run: npm install -g snyk
      
    - name: Run Snyk security scan
      run: snyk test --all-projects
