name: Snyk Security Scan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Snyk CLI
      run: npm install -g snyk
      
    - name: Run Snyk security scan
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk test --all-projects --org=6ce58cdd-2e65-4c0c-bbe5-705980cee5fe || true
        echo Prueba despues del test
        TEST_RESULT=$?
        echo "$TEST_RESULT"
        if [ $TEST_RESULT == 0 ]; then
          echo "No vulnerabilities found."
        else
          echo "Vulnerabilities found. Reverting to previous version..."
          git reset --hard HEAD^
          git push -f
        fi
