name: Snyk Security Scan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
      
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Snyk CLI
      run: npm install -g snyk
      
    - name: Run Snyk security scan
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --all-projects
