name: Snyk Security Scan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Snyk CLI
      run: npm install -g snyk
      
    - name: Run Snyk security scan
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --all-projects --json > snyk_results.json

    - name: Check Snyk results
      run: |
        if grep -q "No known vulnerabilities found" snyk_results.json; then
          echo "Las pruebas de Snyk pasaron. Puedes subir tus cambios."
        else
          echo "Se encontraron vulnerabilidades en el código. No se permitirá la subida."
          exit 1
        fi
